apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: k8s-course
  name: app-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: disk-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8s-course
  name: log-dir-pvc
spec:
  volumeName: app-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
# not possible to create many PVCs to one PV
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#binding
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  namespace: k8s-course
#  name: log-dir-ro-pvc
#spec:
#  volumeName: app-storage
#  accessModes:
#    - ReadOnlyMany
#  resources:
#    requests:
#      storage: 1Gi
