apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: k8s-course
  name: app-storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  nfs:
    server: nfs-server.k8s-course.svc.cluster.local
    path: "/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8s-course
  name: log-dir-pvc
spec:
  volumeName: app-storage
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
# not possible to create many PVCs to one PV
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#binding
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  namespace: k8s-course
#  name: log-dir-ro-pvc
#spec:
#  volumeName: app-storage
#  storageClassName: ""
#  accessModes:
#    - ReadOnlyMany
#  resources:
#    requests:
#      storage: 1Gi
