spring:
  security:
    user:
      name: testuser
      password: testpassword
  redis:
    host: "localhost"
    port: 6379
log:
  message: "this is default logging message"
management:
  endpoints:
    web:
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
---
spring:
  profiles: prod
  security:
    user:
      name: ${RANDOM_APP_USER}
      password: ${RANDOM_APP_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: 6379

logging:
  file:
    name: "/usr/share/logs/random-init/random-app.log"
    total-size-cap: "40MB"
log:
  message: ${LOG_MESSAGE}
