apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: ns-rs
  name: k8s-course
  labels:
    app: k8s-course
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-course
      labels:
        app: k8s-course
    spec:
      containers:
        - name: random-app
          image: eu.gcr.io/kuber-training-272213/random-app:v20
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /random-app/hello
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /random-app/hello
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 180
          env:
            - name: RANDOM_APP_USER
              valueFrom:
                secretKeyRef:
                  name: random-app-secret
                  key: app-user
            - name: RANDOM_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: random-app-secret
                  key: app-pass
            - name: LOG_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: random-app-config
                  key: log-message
            - name: REDIS_HOST
              value: redis-service
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
      restartPolicy: Always
  selector:
    matchLabels:
      app: k8s-course


