apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: random-app
  namespace: ns-d
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-course
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 10