apiVersion: v1
kind: Service
metadata:
  name: k8s-course
  namespace: ns-d
spec:
  selector:
    app: k8s-course
  ports:
    - name: tomcat
      port: 8080
      targetPort: 8080
      protocol: TCP
#  type: LoadBalancer
  type: NodePort